# Generated by Django 2.2.7 on 2019-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boatshop_api', '0004_remove_orderboat_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderboat',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
