# Generated by Django 2.2.7 on 2019-11-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boatshop_api', '0005_orderboat_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boat',
            name='price',
            field=models.FloatField(blank=True),
        ),
    ]
